defaults: &defaults 
  working_directory: ~/room-service-app
  docker:
    - image: circleci/node:8.11.2

version: 2
jobs:
  deploy-staging:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache
      - run: 
          name: Install packages
          command: yarn
      - save_cache:
          key: dependency-cache
          paths:
            - ~/.cache/yarn
      - run: 
          name: Rebuild node-sass
          command: npm rebuild node-sass
      - run: 
          name: Install aws command line
          command: sudo apt-get update && sudo apt-get install -y awscli
      - run:
          name: Deploy Staging
          command: ENV=staging yarn build && aws s3 cp --recursive ./build s3://room-service-staging.handytravel.tech --region ap-southeast-1
  deploy-uat:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache
      - run: 
          name: Install packages
          command: yarn
      - save_cache:
          key: dependency-cache
          paths:
            - ~/.cache/yarn
      - run: 
          name: Rebuild node-sass
          command: npm rebuild node-sass
      - run: 
          name: Install aws command line
          command: sudo apt-get update && sudo apt-get install -y awscli
      - run:
          name: Deploy UAT
          command: ENV=uat yarn build && aws s3 cp --recursive ./build s3://room-service-uat.handytravel.tech --region ap-southeast-1
  deploy-dev:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache
      - run: 
          name: Install packages
          command: yarn
      - save_cache:
          key: dependency-cache
          paths:
            - ~/.cache/yarn
      - run: 
          name: Rebuild node-sass
          command: npm rebuild node-sass
      - run: 
          name: Install aws command line
          command: sudo apt-get update && sudo apt-get install -y awscli
      - run:
          name: Deploy DEV
          command: ENV=development yarn build && aws s3 cp --recursive ./build s3://room-service-dev.handytravel.tech --region ap-southeast-1
  deploy-production:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache
      - run: 
          name: Install packages
          command: yarn
      - save_cache:
          key: dependency-cache
          paths:
            - ~/.cache/yarn
      - run: 
          name: Rebuild node-sass
          command: npm rebuild node-sass
      - run: 
          name: Install aws command line
          command: sudo apt-get update && sudo apt-get install -y awscli
      - run:
          name: Deploy Production
          command: ENV=production yarn build && aws s3 cp --recursive ./build s3://room-service.handy.travel --region ap-southeast-1

workflows:
  version: 2
  build_and_test:
    jobs:
      - deploy-staging:
          filters:
            branches:
              only: staging
      - deploy-uat:
          filters:
            branches:
              only: uat
      - deploy-dev:
          filters:
            branches:
              only: dev
      - deploy-production:
          filters:
            branches:
              only: master
